#!/usr/bin/env python3
"""One-shot bridge from the legacy publication tree to the Astro/OKF foundation.

This script is intentionally temporary. It gives every canonical public article
an explicit OKF type, keeps the legacy Jekyll mirror synchronized while it still
serves production, validates the bundle with okf-parser, and materializes the
Astro-targeted Zod contract generated by the parser.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARTICLES = ROOT / "content" / "articles"
GENERATED_SCHEMA = ROOT / "src" / "generated" / "okf-schema.ts"
OKF_VERSION = "0.45.1"
SPEC_TEMPLATE = "docs/types/{slug}.md"
EXCLUDED_SPECS = "docs/types/**"


def add_public_article_type(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise RuntimeError(f"{path}: missing YAML frontmatter")
    try:
        frontmatter, rest = text[4:].split("\n---\n", 1)
    except ValueError as exc:
        raise RuntimeError(f"{path}: unterminated YAML frontmatter") from exc

    type_lines = [line for line in frontmatter.splitlines() if line.startswith("type:")]
    if type_lines:
        if type_lines != ["type: PublicArticle"]:
            raise RuntimeError(f"{path}: unexpected OKF type: {type_lines!r}")
        return False

    path.write_text(
        "---\ntype: PublicArticle\n" + frontmatter + "\n---\n" + rest,
        encoding="utf-8",
    )
    return True


def run(*args: str, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args,
        cwd=ROOT,
        check=True,
        text=True,
        capture_output=capture,
    )


def main() -> int:
    changed = [path for path in sorted(ARTICLES.glob("*.md")) if add_public_article_type(path)]
    if changed:
        print(f"typed {len(changed)} canonical PublicArticle documents")

    # Keep production Jekyll healthy until the cutover PR removes this mirror.
    run("python", "scripts/build-publication.py")

    # Use the published parser version already consumed by Astronauta. This
    # release includes the Astro-specific Zod target, so presentation still
    # consumes the parser's semantic contract without compiling a source checkout.
    okf = ("uvx", "--from", f"okf-parser=={OKF_VERSION}", "okf-parser")
    run(
        *okf,
        "check",
        "content",
        "--exclude",
        EXCLUDED_SPECS,
        "--require-spec",
        SPEC_TEMPLATE,
        "--normative-spec",
    )
    generated = run(
        *okf,
        "schema",
        "content",
        "--format",
        "zod",
        "--zod-import",
        "astro",
        "--infer-types",
        "--exclude",
        EXCLUDED_SPECS,
        capture=True,
    ).stdout

    if "export const PublicArticleSchema" not in generated:
        raise RuntimeError("okf-parser did not emit PublicArticleSchema")
    if "from 'astro:content'" not in generated:
        raise RuntimeError("okf-parser did not emit the Astro Zod import target")

    GENERATED_SCHEMA.parent.mkdir(parents=True, exist_ok=True)
    previous = GENERATED_SCHEMA.read_text(encoding="utf-8") if GENERATED_SCHEMA.exists() else None
    if generated != previous:
        GENERATED_SCHEMA.write_text(generated, encoding="utf-8")
        print(f"wrote {GENERATED_SCHEMA.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
